// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbz1ICSvg_ZHhF749SoEOWAwKIyeNygpo',
    appId: '1:72294916291:web:56c7c55f1745a7cd624276',
    messagingSenderId: '72294916291',
    projectId: 'fittracker-b6c70',
    authDomain: 'fittracker-b6c70.firebaseapp.com',
    storageBucket: 'fittracker-b6c70.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4w9q-t78P6Bh65CZSKDyavlSHHnkptP4',
    appId: '1:72294916291:android:d90b77ee9a77fd6b624276',
    messagingSenderId: '72294916291',
    projectId: 'fittracker-b6c70',
    storageBucket: 'fittracker-b6c70.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgDEPjUHbruTnL24aQR3QmV2PaeR0l3fc',
    appId: '1:72294916291:ios:ffde1ea2ed8707a6624276',
    messagingSenderId: '72294916291',
    projectId: 'fittracker-b6c70',
    storageBucket: 'fittracker-b6c70.firebasestorage.app',
    iosBundleId: 'com.example.fittracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgDEPjUHbruTnL24aQR3QmV2PaeR0l3fc',
    appId: '1:72294916291:ios:ffde1ea2ed8707a6624276',
    messagingSenderId: '72294916291',
    projectId: 'fittracker-b6c70',
    storageBucket: 'fittracker-b6c70.firebasestorage.app',
    iosBundleId: 'com.example.fittracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbz1ICSvg_ZHhF749SoEOWAwKIyeNygpo',
    appId: '1:72294916291:web:7041f5de677056fa624276',
    messagingSenderId: '72294916291',
    projectId: 'fittracker-b6c70',
    authDomain: 'fittracker-b6c70.firebaseapp.com',
    storageBucket: 'fittracker-b6c70.firebasestorage.app',
  );

}